#!/usr/bin/env tsx
/**
 * Regenerates `docs/verification-ledger.md` from `@unverified-live` /
 * `@verified-live(YYYY-MM-DD)` JSDoc markers on real-adapter methods under
 * `src/adapters/**\/real.ts` (architecture.md §2, §9). The honesty ledger is only worth
 * anything if it cannot silently drift from the code — `--check` mode exits 1 if the
 * committed file differs from what would be generated, and CI runs that mode.
 *
 * Usage:
 *   pnpm gen:ledger          # regenerate docs/verification-ledger.md in place
 *   pnpm gen:ledger --check  # verify it's already up to date; exit 1 if not
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const ADAPTERS_DIR = path.join(ROOT, 'src', 'adapters');
const OUTPUT_PATH = path.join(ROOT, 'docs', 'verification-ledger.md');

interface MethodEntry {
  adapter: string;
  method: string;
  status: 'unverified-live' | 'verified-live';
  verifiedDate?: string;
}

// Matches a JSDoc comment containing a marker, immediately followed (across blank space)
// by a method-looking declaration: `async name(`, `name(`, or `get name(`.
const MARKER_RE =
  /\/\*\*([^*]|\*(?!\/))*?(@unverified-live|@verified-live\((\d{4}-\d{2}-\d{2})\))([^*]|\*(?!\/))*?\*\/\s*\n\s*(?:public\s+|private\s+|protected\s+|readonly\s+|static\s+|async\s+|get\s+|set\s+)*([a-zA-Z_$][\w$]*)\s*\(/g;

async function findRealAdapterFiles(): Promise<string[]> {
  const adapterDirs = await readdir(ADAPTERS_DIR, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of adapterDirs) {
    if (!entry.isDirectory()) continue;
    const candidate = path.join(ADAPTERS_DIR, entry.name, 'real.ts');
    try {
      await readFile(candidate);
      files.push(candidate);
    } catch {
      // no real.ts in this adapter directory — fine, not every port has one yet.
    }
  }
  return files.sort();
}

function extractEntries(adapterName: string, source: string): MethodEntry[] {
  const entries: MethodEntry[] = [];
  MARKER_RE.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = MARKER_RE.exec(source))) {
    const isVerified = match[2]?.startsWith('@verified-live');
    entries.push({
      adapter: adapterName,
      method: match[5] ?? '(unknown)',
      status: isVerified ? 'verified-live' : 'unverified-live',
      verifiedDate: match[3],
    });
  }
  return entries;
}

function renderMarkdown(entriesByFile: Map<string, MethodEntry[]>): string {
  const lines: string[] = [];
  lines.push('# Verification Ledger');
  lines.push('');
  lines.push(
    '**Generated by `scripts/gen-verification-ledger.ts` — do not edit by hand.** Run ' +
      '`pnpm gen:ledger` to regenerate after adding or changing a `@unverified-live` / ' +
      '`@verified-live(YYYY-MM-DD)` marker in `src/adapters/**/real.ts`. CI runs ' +
      '`pnpm gen:ledger --check` and fails if this file is out of date (architecture.md §9).',
  );
  lines.push('');

  let totalUnverified = 0;
  let totalVerified = 0;
  for (const entries of entriesByFile.values()) {
    for (const e of entries) {
      if (e.status === 'verified-live') totalVerified += 1;
      else totalUnverified += 1;
    }
  }
  lines.push(
    `**Live call summary: ${totalVerified} verified-live, ${totalUnverified} unverified-live.**`,
  );
  lines.push('');

  for (const [file, entries] of entriesByFile) {
    const relPath = path.relative(ROOT, file);
    lines.push(`## \`${relPath}\``);
    lines.push('');
    if (entries.length === 0) {
      lines.push('_No `@unverified-live` / `@verified-live` markers found in this file._');
      lines.push('');
      continue;
    }
    lines.push('| Method | Status | Verified on |');
    lines.push('|---|---|---|');
    for (const e of entries) {
      lines.push(`| \`${e.method}\` | ${e.status} | ${e.verifiedDate ?? '—'} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

async function generate(): Promise<string> {
  const files = await findRealAdapterFiles();
  const entriesByFile = new Map<string, MethodEntry[]>();
  for (const file of files) {
    const source = await readFile(file, 'utf8');
    const adapterName = path.basename(path.dirname(file));
    entriesByFile.set(file, extractEntries(adapterName, source));
  }
  return renderMarkdown(entriesByFile);
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const generated = await generate();

  if (check) {
    let existing: string | undefined;
    try {
      existing = await readFile(OUTPUT_PATH, 'utf8');
    } catch {
      existing = undefined;
    }
    if (existing !== generated) {
      console.error(
        `gen:ledger --check: ${path.relative(ROOT, OUTPUT_PATH)} is out of date. Run \`pnpm gen:ledger\` and commit the result.`,
      );
      process.exit(1);
    }
    console.log('gen:ledger --check: docs/verification-ledger.md is up to date.');
    return;
  }

  await writeFile(OUTPUT_PATH, generated);
  console.log(`gen:ledger: wrote ${path.relative(ROOT, OUTPUT_PATH)}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
