import { randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream, mkdirSync } from 'node:fs';
import { stat as fsStat, unlink } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';
import { PassThrough, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import type { BlobStagingPort } from '../../ports/blob-staging.js';
import { NotFoundError } from '../../ports/errors.js';

/** Only ever true for a server-generated `newId()` — a defense-in-depth check, not the
 * source of safety: no caller ever passes user input here (architecture.md §10). */
const SAFE_ID_RE = /^[a-zA-Z0-9_-]+$/;

/**
 * Real local-disk `BlobStagingPort` (architecture.md §2, §6). Every id is generated by
 * `newId()` (a UUID) — never derived from a client-supplied filename — and every write is
 * streamed straight to disk via `node:stream/promises` `pipeline`, so `POST /api/files`
 * never buffers a whole upload in memory regardless of `MAX_UPLOAD_BYTES`.
 */
export class LocalDiskBlobStaging implements BlobStagingPort {
  constructor(private readonly dir: string) {}

  newId(): string {
    return randomUUID();
  }

  private pathFor(id: string): string {
    if (!SAFE_ID_RE.test(id)) {
      throw new Error(`LocalDiskBlobStaging: refusing unsafe staging id ${JSON.stringify(id)}`);
    }
    return path.join(this.dir, id);
  }

  async put(id: string, stream: Readable): Promise<{ bytes: number }> {
    // Synchronous on purpose: if a caller already started flowing `stream` into a
    // pre-attached transform (e.g. `Files.createStaged`'s byte-cap limiter) before
    // calling `put`, any `await` here would open a window where that upstream transform
    // could already emit data — or an error — before `pipeline()` below has attached its
    // listeners, since `Readable#pipe()` starts flowing synchronously. A one-time,
    // idempotent `mkdirSync` costs nothing measurable next to a multi-MB upload and
    // closes that window entirely.
    mkdirSync(this.dir, { recursive: true });
    const dest = this.pathFor(id);
    let bytes = 0;
    const counter = new Transform({
      transform(chunk: Buffer, _enc, callback) {
        bytes += chunk.length;
        callback(null, chunk);
      },
    });
    await pipeline(stream, counter, createWriteStream(dest));
    return { bytes };
  }

  async open(id: string): Promise<Readable> {
    const target = this.pathFor(id);
    try {
      await fsStat(target);
    } catch {
      throw new NotFoundError(`staging blob not found: ${id}`);
    }
    // Route through a PassThrough so callers always get a plain, generic Readable
    // (matching the port's type) rather than a fs.ReadStream with filesystem-specific
    // methods callers should never depend on.
    const out = new PassThrough();
    createReadStream(target).pipe(out);
    return out;
  }

  async stat(id: string): Promise<{ bytes: number } | undefined> {
    try {
      const info = await fsStat(this.pathFor(id));
      return { bytes: info.size };
    } catch {
      return undefined;
    }
  }

  async remove(id: string): Promise<void> {
    try {
      await unlink(this.pathFor(id));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }
}
